### ISSUE TITLE
Hotfix branch not working

### ISSUE THREAD

**Issue by angelcervera** [stewartHutchins/scalatest-maven-plugin-bug-demo#2]
Are you sure that the hotfix branch is working?

I'm getting this error when `mvn clean test`
```
java.lang.ClassNotFoundException: org.scalatest.tools.Runner
```

```
> mvn -v
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /home/angelcc/apps/apache-maven-3.8.4
Java version: 11.0.15, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-30-generic", arch: "amd64", family: "unix"

```

**Comment by stewartHutchins** [comment]
It seems to work - though I haven't copied your environment exactly.

On the `master` branch `mvn clean test` in the same directory as the root pom fails with the expected error in the root module.
After switching to the `hotfix` branch `mvn clean test` from the same directory as the root pom will not fail.
Switching back to the `master` branch and repeating yields the same error.

Please double check that you're on the correct branch and that you're running commands from the root directory.
